import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "تسجيل الدخول",
          "2": "Gombal",
          "3": "اكتشف أسلوبك",
          "4": "احصل على منتجات عالية الجودة وأنيقة بأسعار معقولة جدًا.",
          "5": "الدخول باستخدام جوجل",
          "6": "الدخول باستخدام الفيسبوك",
          "7": "الدخول باستخدام ابل",
          "8": "صباح الخير ☀️",
          "9": " دعونا نحصل على شيء",
          "10": "احصل على خصم يصل إلى 50٪",
          "11": "احصل على خصم كبير في وقت محدود للغاية ، ماذا تنتظر تسوق الآن!",
          "12": "فئات",
          "13": "قميص أسود أكابيلا",
          "14": "قميص أبيض أكابيلا",
          "15": "العناصر",
          "16": "الحجم",
          "17": "الفيزا",
          "18": "قميص شاطئ أكابيلا",
          "19": "ابحث عن اسم مدينتك أو شارعك",
          "20": "الولايات المتحدة الأمريكية ، مدينة نيويورك",
          "21": "32 شارع هانكوك",
          "22": "اذهب إلى الدفع",
          "23": "الدفع",
          "24": "أضف بطاقة ائتمان",
          "25": "اسم البطاقة",
          "26": "اكتب هنا",
          "27": "رقم البطاقة",
          "28": "تاريخ الانتهاء",
          "29": "CVV",
          "30": "بطاقتك الائتمانية",
          "31": "بطاقة إئتمان",
          "32": "EXP",
          "33": "مراجعة الطلب",
          "34": "الاسم",
          "35": "رقم الهاتف",
          "36": "العنصر",
          "37": "المجموع",
          "38": "العنوان",
          "39": "شحن",
          "40": "اشتري الآن",
          "41": "البحث الأخير",
          "42": "Kick Denim",
          "43": "Kiddrock",
          "44": "Sypilizz",
          "45": "Cowboy hat",
          "46": "Masha",
          "47": "الأكثر مبيعًا",
          "48": "سجل البحث",
          "49": "البحث",
          "50": "أرخص",
          "51": "منتهي",
          "52": "إعادة تعيين إلى الافتراضي",
          "53": "وضع رزمة",
          "54": "الرزم",
          "55": "أرسل",
          "56": "تم التوصيل",
          "57": "ألغيت",
          "58": "العناصر الخاصة بك",
          "59": "شحنة",
          "60": "تفاصيل",
          "61": "FedEx Express",
          "62": "اليوم المقدر: ١٣-١٦ حزيران يونيو",
          "63": "من:",
          "64": "709 Faeh Ave",
          "65": "الى:",
          "66": "الحزمة الخاصة بك لا تزال في التعبئة",
          "67": "الغاء الطلب",
          "68": "الاعدادات",
          "69": "الحساب",
          "70": "Wildan Justin",
          "71": "اللغة",
          "72": "تعديل العنوان",
          "73": "تحرير بطاقة الائتمان",
          "74": "الاشعارات",
          "75": "الوضع المظلم",
          "76": "لا تتردد في السؤال ، نحن على استعداد للمساعدة!",
          "77": "خروج",
          "78": "تعديل الملف الشخصي",
          "79": "تغيير الصورة",
          "80": "الاسم الأول",
          "81": "اسم العائلة",
          "82": "اسم المستخدم",
          "83": "الحنس",
          "84": "الهاتف المحمول",
          "85": "الايميل",
          "86": "تأكيد",
          "87": "اختار اللغة",
          "88": "إنجليزي",
          "89": "العربية",
          "90": "تايلاند",
          "91": "اليابان",
          "92": "صينى",
          "93": "هل أنت متأكد من تغيير اللغة؟",
          "94": "نعم",
          "95": "لا",
          "96":"وضع النهار"
        },
        "en": {
          "1": "Sign In",
          "2": "Gombal",
          "3": "Discover you style",
          "4": "Get quality and classy products at very affordable prices.",
          "5": "Sign in with Google",
          "6": "Sign in with Facebook",
          "7": "Sign in with Apple",
          "8": "Good Morning ☀️",
          "9": "Let’s got something",
          "10": "Get discount up to 50%",
          "11":
              "Get a big discount with a very limited time,what are you waiting for shop now!",
          "12": "Categories",
          "13": "Acapella Black Shirt",
          "14": "Acapella White Shirt",
          "15": "Items",
          "16": "Size",
          "17": "Cart",
          "18": "Acapella Beach Shirt",
          "19": "Search your City or street name  ",
          "20": "USA, New York City",
          "21": "32, Hancock St",
          "22": "Go to payment",
          "23": "Payment",
          "24": "Add credit card",
          "25": "Card name",
          "26": "Write here",
          "27": "Card number",
          "28": "Expiry date",
          "29": "CVV",
          "30": "Your credit card",
          "31": "Credit Card",
          "32": "EXP",
          "33": "Order Review",
          "34": "Name",
          "35": "Number phone",
          "36": "Item",
          "37": "Total",
          "38": "Address",
          "39": "Shipping",
          "40": "Buy now",
          "41": "Last search",
          "42": "Kick Denim",
          "43": "Kiddrock",
          "44": "Sypilizz",
          "45": "Cowboy hat",
          "46": "Masha",
          "47": "Best seller",
          "48": "Filter Search",
          "49": "Search",
          "50": "Cheapest",
          "51": "Done",
          "52": "Reset to default",
          "53": "Package status",
          "54": "Packaging",
          "55": "Sent",
          "56": "Delivered",
          "57": "Canceled",
          "58": "Your items",
          "59": "Shipment",
          "60": "Details",
          "61": "FedEx Express",
          "62": "Estimated day: 13 - 16 Jun",
          "63": "From :",
          "64": "709 Faeh Ave",
          "65": "To:",
          "66": "Your package is still in packing",
          "67": "Cancel order",
          "68": "Settings",
          "69": "Account",
          "70": "Wildan Justin",
          "71": "Language",
          "72": "Edit address",
          "73": "Edit credit card",
          "74": "Notification",
          "75": "Dark mode",
          "76": "Feel free to ask, We ready to help!",
          "77": "Sign out",
          "78": "Edit profile",
          "79": "Change image",
          "80": "First name",
          "81": "Last name",
          "82": "Username",
          "83": "Gender",
          "84": "Hand phone",
          "85": "Email",
          "86": "Confirm",
          "87": "Select language",
          "88": "English",
          "89": "Arabic",
          "90": "Thailand",
          "91": "Japan",
          "92": "Chinese",
          "93": "Are you sure you want to change?",
          "94": "Yes",
          "95": "No",
          "96":"Light Mode"
        }
      };
}
//